name: Build on push
on: [push]

jobs:
  rolling_release:
    runs-on: ubuntu-latest
    name: Rolling Release on Branch
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: use gh
        run: gh auth status
      - uses: nicovince/manage-release@823e1adff6fd1836520379f7b4fa6f6970961102
        with:
          files: manage-release.sh
